### ISSUE TITLE
Hide similar results if there are not.

### ISSUE THREAD

**Issue by ael-code** [insomnia-lab/libreant#10]
Similar results should be shown only if they are not empty

**Comment by boyska** [comment]
Can you provide a simple way to reproduce this?

**Comment by ael-code** [comment]
Reproducing steps:
 - add an item with only one field ```nomlt_2358: nomlt_2358```
 - find the id of the item
 - open /view/<id>

similar results section will be empty.

**Comment by ael-code** [comment]
fixed by #33

**Comment by boyska** [comment]
for reference: see #33
