### ISSUE TITLE
rewrite cli

### ISSUE THREAD

**Issue by ael-code** [insomnia-lab/libreant#107]
We discussed a lot about cli implementation in #67.

I think we can start discussing about which library ( independent from Flask ) we will use to rewrite cli stuff.

There are a lot of stuff out there. You can find some libraries [here]( http://docs.python-guide.org/en/latest/scenarios/cli/)

**Comment by boyska** [comment]
At the moment, the core is tightly bound to flask. So code reorganization should come first.

**Comment by boyska** [comment]
btw, click seems so cool :D http://click.pocoo.org/3/

**Comment by ael-code** [comment]
I'm writing the new cli.
At the moment I'm working on `libreant-db` the command that provide access to the db. I'm wondering which operations this command should provide.

 - export volume
 - export all volumes
 - simple search
 - import volumes

**Comment by boyska** [comment]
The new `iterate_all_volumes` seems a good candidate. I think that a simple approach is having some commands to *get* VolumeIDs and some other to *export* volume given their VolumeID.

So for example `search` could just get the VolumeID, which is then shown via the `export` command.

I think that we need something to handle attachments, but we could postpone this. See #75
