### ISSUE TITLE
add page | warn if javascript is disable

### ISSUE THREAD

**Issue by ael-code** [insomnia-lab/libreant#112]
if the client browser does not support javascript, the add page will be useless. We should warn the user about that.

**Comment by boyska** [comment]
Is there a (nice) way to do so inside the page? Sure, we can just say it in the documentation, but immediate error message is way more effective.

**Comment by ael-code** [comment]
The web page alert is the solution.

**Comment by boyska** [comment]
Yes, but you need to have a nice alert without using js! I believe that there could be a trick to do it, it's just that I don't know it.

**Comment by ael-code** [comment]
no problem. I'll try.
