### ISSUE TITLE
testing documentation

### ISSUE THREAD

**Issue by ael-code** [insomnia-lab/libreant#113]
With #103 we changed the way we test.
We need to update the current documentation about testing in the ```README``` or insert a new section in the [how to develop](http://libreant.readthedocs.org/en/latest/developer.html) chapter.

New command for testing:
```python setup.py test```

**Comment by boyska** [comment]
In the document you linked, the command is clearly written.

**Comment by ael-code** [comment]
I think we can highlight that part in the official doc ( readTheDoc ) and remove old steps from the README. What do you think about it?

**Comment by boyska** [comment]
seems correct

**Comment by ael-code** [comment]
If we add new tests somewhere in the code, do we need to update the ```cover-package=``` directive in ```/setup.cfg```?
Nosetest provides any automatic way of collecting tests ?
Why that file have been called ```setup.cfg``` ? Could it contains others settings then nosetest ones ?

**Comment by boyska** [comment]
>If we add new tests somewhere in the code, do we need to update the ```cover-package=``` directive in ```/setup.cfg```?

cover-package must be updated when new _packages_ are updated.

>Nosetest provides any automatic way of collecting tests ?

yes, inside of the specified packages

>Why that file have been called ```setup.cfg``` ? Could it contains others settings then nosetest ones ?

exactly. It is the configuration place for setuptools. As you can see,
it is organized in sections; nosetests is one (and currently the only
one) of them.
