### ISSUE TITLE
general description missing in rtfd

### ISSUE THREAD

**Issue by ael-code** [insomnia-lab/libreant#124]
At the moment the [about section](http://libreant.readthedocs.org/en/latest/about.html) in the rtfd says "libreant is ubercool".

I think that the upgrade time for this section is arrived.

**Comment by leonaard** [comment]
@g3-3k pushed an updated about.rst with #149, shall we close this?

**Comment by ael-code** [comment]
> @g3-3k pushed an updated about.rst with #149, shall we close this?

yes

**Comment by boyska** [comment]
despite it's right to close this, I'm not really satisfied with such a general description.

I would have liked it to be clearer about "why libreant is good for me", and less about "give me some cool technical details".

**Comment by ael-code** [comment]
On 06/07/2015 12:41 PM, BoySka wrote:
> despite it's right to close this, I'm not really satisfied with such a
> general description.
> 
> I would have liked it to be clearer about "why libreant is good for me",
> and less about "give me some cool technical details".
> 

I agree.
-- 
tommy.ael
gpg key: 0xEBD8B3682C4C4645

**Comment by g3-3k** [comment]
We should contact a convincer.
I ll try to improve the presentation

**Comment by ael-code** [comment]
On 06/07/2015 01:03 PM, cocco->nat wrote:
> We should contact a convincer.
> I ll try to improve the presentation
> 

Please do not commit directly on the branch master of insomnialab.

-- 
tommy.ael
gpg key: 0xEBD8B3682C4C4645

**Comment by g3-3k** [comment]
too easy to do!? :)

On 06/07/2015 02:48 PM, ael wrote:
>
>
> On 06/07/2015 01:03 PM, cocco->nat wrote:
> > We should contact a convincer.
> > I ll try to improve the presentation
> >
>
> Please do not commit directly on the branch master of insomnialab.
>
> -- 
> tommy.ael
> gpg key: 0xEBD8B3682C4C4645
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/insomnia-lab/libreant/issues/124#issuecomment-109748860>.
>

-- 
Easy is the way for the Dark Side
mit dot eu
0xDF6EA30E
