### ISSUE TITLE
fsdb upgraded to v0.3

### ISSUE THREAD

**Issue by ael-code** [insomnia-lab/libreant#131]
fsdb update introduced breaking chenges.

We should quickly release a new version that fix the fsdb version dependency and then change code in order to use the latest fsdb release

**Comment by boyska** [comment]
wait, wait. We can force the version we need in setup.py, for example using `Fsdb==0.2` instead of `Fsdb`. I think this is the most immediate solution.

Of course after that we should find a way to use the improvements of Fsdb 0.3

**Comment by ael-code** [comment]
> wait, wait. We can force the version we need in setup.py, for example using Fsdb==0.2 instead of Fsdb. I think this is the most immediate solution.
> 
> Of course after that we should find a way to use the improvements of Fsdb 0.3

This is exactly what I mean. I used fix as "fissare" ;)

**Comment by boyska** [comment]
ok! can you do it? (btw, I don't know the exact version we should depend upon, do you?)

**Comment by ael-code** [comment]
released libreant version 0.1.3 with ```Fsdb==0.2.5```
