### ISSUE TITLE
custom 404 error page

### ISSUE THREAD

**Issue by ael-code** [insomnia-lab/libreant#136]
We are using the default 404 error page provided by flask.
To see an example visit:
http://10.10.2.21:5000/asdasd

Will be nice to have a custom 404 error page.

**Comment by boyska** [comment]
why reopening?

**Comment by ael-code** [comment]
The code that closed this issue was not revisioned. 
I'm going to clean last commits on branch master and we will reintroduce commits through standard method: revisionable pull request.

**Comment by boyska** [comment]
https://www.youtube.com/watch?v=Q3_2entulkw

shouldn't we just review the code and, in case we are not sure, revert?

**Comment by ael-code** [comment]
On 06/06/2015 07:39 PM, BoySka wrote:
> https://www.youtube.com/watch?v=Q3_2entulkw
> 
> shouldn't we just review the code and, in case we are not sure, revert?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/insomnia-lab/libreant/issues/136#issuecomment-109622226>.
> 

The commits history is dirty.

-- 
tommy.ael
gpg key: 0xEBD8B3682C4C4645

**Comment by boyska** [comment]
>The commits history is dirty.

what do you mean? I think I am missing something

**Comment by ael-code** [comment]
@leonaard I revert your changes from branch master. I hope you'll open a valid pr soon ;)

**Comment by boyska** [comment]
Really, is it needed?

**Comment by ael-code** [comment]
solved in #155
