### ISSUE TITLE
Implement "recently added" section

### ISSUE THREAD

**Issue by ael-code** [insomnia-lab/libreant#14]

**Comment by ael-code** [comment]
added api to request last items added into db ( #18 )

Missing:
 - route on webant ( will serve also json response )
 - web interface access point

**Comment by boyska** [comment]
Missing parts:
* document in the code how does that work (that is, provide a link to opensearch documentation)
* expose it in the website

**Comment by ael-code** [comment]
which route we will use for this function? ```/recent```?

**Comment by ael-code** [comment]
I am starting to implement this under ```/recents```
