### ISSUE TITLE
make possible to use libreant as metadata-only library

### ISSUE THREAD

**Issue by ael-code** [insomnia-lab/libreant#176]
At the moment it's not possible to easily use libreant as metadata-only library. This is because fsdb instance is always initialized and the relative `FSDB_PATH` parameter is mandatory. If you don't want to use libreant for storing binary files you have to put in place a trick, you have to pass a dummy path as `FSDB_PATH`, then fsdb will be initialized but you will not use it.

**Comment by leonaard** [comment]
Done (#180)
