### ISSUE TITLE
Preview for new item

### ISSUE THREAD

**Issue by g3-3k** [insomnia-lab/libreant#178]
Just before add a new item, once all fields are compiled and the "add item" button is pressed, we should offer a preview of all metadata and the possibility of change it.

**Comment by boyska** [comment]
should we? I mean, probably the preview will be _very_ similar to the form they filled in, so what's the point of this?

**Comment by ael-code** [comment]
According to me we can close this for now.

**Comment by boyska** [comment]
@g3-3k if you have an idea about a common case in which preview is desirable, please re-open this issue.
