### ISSUE TITLE
actors preview on item

### ISSUE THREAD

**Issue by g3-3k** [insomnia-lab/libreant#179]
When you set as custom key "actors" it offer a preview of authors, this is good but it assume it as a list, so a simple astring as "aiuola" will be "a,i,l,o,u".

**Comment by ael-code** [comment]
this is related to #39

**Comment by boyska** [comment]
I don't think this issue should be open. As @ael-code pointed out, #39 is the right way of fixing it. #178 can be useful too.

Having a preview only for actors doesn't sound right.
