### ISSUE TITLE
error on libreant-db

### ISSUE THREAD

**Issue by g3-3k** [insomnia-lab/libreant#194]
ho provato a  cercare e cancellare un libro e succede questo!

>~/coder/libreant (git)-[remotes/origin/HEAD] % sudo libreant-db -d search ciao                                                         :(
>Traceback (most recent call last):
 > File "/usr/local/bin/libreant-db", line 5, in <module>
>    from pkg_resources import load_entry_point
>  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3084, in <module>
>    @_call_aside
>  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3070, in _call_aside
>    f(*args, **kwargs)
>  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3097, in >_initialize_master_working_set
>    working_set = WorkingSet._build_master()
>  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 651, in _build_master
>    ws.require(__requires__)
>  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 952, in require
>    needed = self.resolve(parse_requirements(requirements))
>  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 839, in resolve
>    raise DistributionNotFound(req, requirers)
>pkg_resources.DistributionNotFound: The 'opensearch' distribution was not found and is required >by libreant

**Comment by boyska** [comment]
On Mon, Oct 05, 2015 at 04:04:29AM -0700, cocco->nat wrote:
>ho provato a  cercare e cancellare un libro e succede questo!
>
>>~/coder/libreant (git)-[remotes/origin/HEAD] % sudo libreant-db -d search ciao

perché sudo? togli sudo e ridicci se dà errore

-- 
boyska

**Comment by ael-code** [comment]
@g3-3k if you are not going to provide additional info please close this issue.
