### ISSUE TITLE
libreant works but doesn t pass tests

### ISSUE THREAD

**Issue by g3-3k** [insomnia-lab/libreant#197]
I cloned a new git repo and followed the instructions
I got this errors but libreant actually works and I can add e download items

Name                            Stmts   Miss  Cover   Missing
-------------------------------------------------------------
archivant.py                        2      0   100%   
archivant/archivant.py            239     22    91%   77, 158, 184, 199, 215, 223-225, 299, 347, 349, 351, 353, 367, 384-387, 390-393
archivant/exceptions.py             4      0   100%   
cli.py                              0      0   100%   
cli/agherant.py                    35     20    43%   19-38, 41
cli/custom_types.py                 8      1    88%   12
cli/libreant.py                    52     31    40%   25-57, 60
cli/libreant_db.py                 74     45    39%   25-48, 55-63, 69-73, 80-87, 93-95, 99
conf.py                             0      0   100%   
conf/config_utils.py               52     12    77%   17-19, 24, 87-95
conf/defaults.py                    9      0   100%   
libreantdb.py                       2      0   100%   
libreantdb/api.py                 107     21    80%   153, 169-177, 180, 192, 195, 200, 203, 227, 257-262, 286-296
presets.py                          2      0   100%   
presets/presetManager.py          136     15    89%   48, 68-69, 74, 79, 88, 91-92, 96-98, 230, 233, 291, 303
users.py                           34      0   100%   
users/models.py                    84      0   100%   
utils.py                            0      0   100%   
utils/loggers.py                   11      8    27%   8-16
webant.py                           2      0   100%   
webant/agherant.py                 46     34    26%   18-33, 37-58, 61-65
webant/agherant_standalone.py      19     11    42%   10-20, 24-25, 28
webant/api.py                       0      0   100%   
webant/api/archivant_api.py       134     97    28%   21-22, 25-26, 28, 44-53, 58-65, 70-74, 79-83, 88-92, 97-121, 126-130, 135-139, 144-149, 154-157, 161-167, 171-181
webant/api/blueprint_api.py        19     10    47%   12-19, 25, 30-31
webant/api/util.py                 14      9    36%   6-10, 13, 17-19
webant/constants.py                 1      0   100%   
webant/util.py                     34     12    65%   11-14, 35-38, 44-47
webant/webant.py                  144     57    60%   57, 75, 88-93, 97-136, 143-146, 159-164, 169-173, 183-184, 202-204, 208, 213, 219, 223-224, 227
webant/webserver_utils.py          15     14     7%   7-22
-------------------------------------------------------------
TOTAL                            1279    419    67%   
----------------------------------------------------------------------
Ran 176 tests in 4.703s

FAILED (errors=84, failures=2)

**Comment by boyska** [comment]
On Wed, Oct 21, 2015 at 01:42:17AM -0700, cocco->nat wrote:
>I cloned a new git repo and followed the instructions
>I got this errors

can you point out which tests are failing, exactly?
hint: it happens sometime that elasticsearch take a lot of time to
start, so elasticsearch-dependent tests could fail just because the
server is still not ready. Please ensure that this is not the case.

>but libreant actually works and I can add e download items

this is not relevant. It could just mean that your test has been too
limited.

-- 
boyska

**Comment by ael-code** [comment]
@g3-3k you was the first to notice this... bravo!
the cause is described in #199

**Comment by g3-3k** [comment]
>@g3-3k you was the first to notice this... bravo!
>the cause is described in #199
Tonight I m gonna sleep better

**Comment by g3-3k** [comment]
>@g3-3k you was the first to notice this... bravo!
>the cause is described in #199

Tonight I m gonna sleep better

**Comment by ael-code** [comment]
solved. The [new release v0.2.2](https://github.com/insomnia-lab/libreant/releases/tag/v0.2.2) that I've made should work
