### ISSUE TITLE
elasticsearch-py has moved to 2.*

### ISSUE THREAD

**Issue by ael-code** [insomnia-lab/libreant#199]
We did not fix the version of `elasticsearch-py` on `setup.py` and now the library has moved to version 2.* that is the one designed to work with elasticsearch 2.
The library has changed a lot so on new installation nothing is gonna work.

**Comment by boyska** [comment]
I think that the correct solution is to specify `elasticsearch==1` on `setup.py`.

**Comment by ael-code** [comment]
> I think that the correct solution is to specify elasticsearch>=1.0.0 on setup.py.
> See https://elasticsearch-py.readthedocs.org/en/master/

I think that the important constraint is the `<2`

**Comment by boyska** [comment]
ops, right!

**Comment by ael-code** [comment]
solved in the hotfix 5fe79e5fc1c76895bfd04d89519aa149959ec69d
