### ISSUE TITLE
new branching model

### ISSUE THREAD

**Issue by ael-code** [insomnia-lab/libreant#201]
I would like our branching model move to a master&develop one.
In this model we'll have a master branch with the tagged and released version and a develop branch in which we'll commit for the upcoming release.

With this model we could easily introduce hotfix, for example we now need to make an hotfix (#200) that should bump the latest official version to `0.2.2` as well as make development version installable.

For a complete description of this branching model you can look at [Vincent Driessen's article](http://nvie.com/posts/a-successful-git-branching-model/)

**Comment by boyska** [comment]
I like the master/develop model, but I would not go too far with it: having a way of pushing hotfixes is good, so I welcome a branch for every minor release, including one for the next minor release (that is, the "develop" thing).

**Comment by ael-code** [comment]
oke we have just switched to the new branching model.
 - `dev`: development branch
 - `master`: latest released version
 - `hotfix-*`: hotfix branches

**Comment by boyska** [comment]
now I am a little confused.
It's clear (I suppose) what's the `dev` branch: it's where everything is happening.
I think you agree with me that there is a `hotfix-*` branch for every minor version. So there will be `hotfix-0.2` or `hotfix-1.4` but no `hotfix-0.2.2`.
Given this, what's `master`? Is it just a sort of alias for the most recent stable version?

I think that it will be nice to provide a small set of "examples" of where one should expect things to happen.

**Comment by ael-code** [comment]
On 10/26/2015 11:09 AM, BoySka wrote:
> now I am a little confused.
> It's clear (I suppose) what's the |dev| branch: it's where everything is
> happening.
Yeap

> I think you agree with me that there is a |hotfix-*| branch for every
> minor version. So there will be |hotfix-0.2| or |hotfix-1.4| but no
> |hotfix-0.2.2|.
Yes I've given the wrong name to the hotfix branch. I will change it
soon to hotfix-0.2.2

> Given this, what's |master|? Is it just a sort of alias for the most
> recent stable version?
> 
The master is the only branch with release tags. As you can see now the
hotfix-* branch include only the bugfix commit but the master include
the tagged commit "bump to v0.2.2".
If this is not clear, you can have a look at the  [Vincent Driessen's
article](http://nvie.com/posts/a-successful-git-branching-model/)
were there is complete examples.

> I think that it will be nice to provide a small set of "examples" of
> where one should expect things to happen.

I think that the [Vincent Driessen's
article](http://nvie.com/posts/a-successful-git-branching-model/) is
well written and he provides the pdf vrsion. We can make a wiki page
with basic infos about this branching model and then links the
Driessen's article.

-- 
tommy.ael
gpg key: 0xEBD8B3682C4C4645

**Comment by boyska** [comment]
On Mon, Oct 26, 2015 at 03:50:29AM -0700, ael wrote:
>On 10/26/2015 11:09 AM, BoySka wrote:
>> I think you agree with me that there is a |hotfix-*| branch for every
>> minor version. So there will be |hotfix-0.2| or |hotfix-1.4| but no
>> |hotfix-0.2.2|.
>Yes I've given the wrong name to the hotfix branch. I will change it
>soon to hotfix-0.2.2

what? I was suggesting the opposite

>> Given this, what's |master|? Is it just a sort of alias for the most
>> recent stable version?
>>
>The master is the only branch with release tags. As you can see now the
>hotfix-* branch include only the bugfix commit but the master include
>the tagged commit "bump to v0.2.2".

Ok, this does not seem very understandable to me.
Let's suppose that we have a 1.0.0 version released, and a 1.1.0
released. We discover a critical bug that affects both versions, and we
fix it. This should produce a 1.0.1 and a 1.1.1.
With the "master" model, how do you do it?
(nope, you should not say "1.0.0 is old, you should have upgraded to
1.1.0" anyway; because upgrading is painful sometimes, and must be done
with care all the times; but hotfixes should be available immediately)

>If this is not clear, you can have a look at the  [Vincent Driessen's
>article](http://nvie.com/posts/a-successful-git-branching-model/)
>were there is complete examples.

So maybe I was getting it wrong. I propose that instead every minor
release get its own branch. I'd call it "release-0.2" rather than
"hotfix-0.2", but it's just naming.
You _create_ that branch from the "develop" branch and that branch will
"contain" the tag "v0.2.0" and all the micro release in that minor
release (like `v0.2.1` `v0.2.2` and so on).
Since every minorrelease branch contains all the tags in the
minorrelease, you can push hotfixes to multiple minorreleases easily.
Everything that is not minorrelease-specific happens in the `develop`
branch. If it's a hotfix, it's cherry-picked inside that branches.

Sorry for having doubled the confusion.
What do you think of my proposal anyway?

**Comment by ael-code** [comment]
On 10/26/2015 12:16 PM, BoySka wrote:
> On Mon, Oct 26, 2015 at 03:50:29AM -0700, ael wrote:
>>On 10/26/2015 11:09 AM, BoySka wrote:
>>> I think you agree with me that there is a |hotfix-*| branch for every
>>> minor version. So there will be |hotfix-0.2| or |hotfix-1.4| but no
>>> |hotfix-0.2.2|.
>>Yes I've given the wrong name to the hotfix branch. I will change it
>>soon to hotfix-0.2.2
> 
> what? I was suggesting the opposite

Oke you are right :):

The hotfix could possibly be merged with many major version in order to
produce multiple minor version (1.0 -> 1.1, 2.1 -> 2.1.1, 3.0 -> 3.1)

Hence it should be named with a general hotfix name not linked to any
particular minor version.

The actual name of the hotfix-elasticsearch-vrs should be fine.

> 
>>> Given this, what's |master|? Is it just a sort of alias for the most
>>> recent stable version?
>>>
>>The master is the only branch with release tags. As you can see now the
>>hotfix-* branch include only the bugfix commit but the master include
>>the tagged commit "bump to v0.2.2".
> 
> Ok, this does not seem very understandable to me.
> Let's suppose that we have a 1.0.0 version released, and a 1.1.0
> released. We discover a critical bug that affects both versions, and we
> fix it. This should produce a 1.0.1 and a 1.1.1.
> With the "master" model, how do you do it?
> (nope, you should not say "1.0.0 is old, you should have upgraded to
> 1.1.0" anyway; because upgrading is painful sometimes, and must be done
> with care all the times; but hotfixes should be available immediately)
> 

I completely agree with you.

>>If this is not clear, you can have a look at the [Vincent Driessen's
>>article](http://nvie.com/posts/a-successful-git-branching-model/)
>>were there is complete examples.
> 
> So maybe I was getting it wrong. I propose that instead every minor
> release get its own branch. I'd call it "release-0.2" rather than
> "hotfix-0.2", but it's just naming.
> You _create_ that branch from the "develop" branch and that branch will
> "contain" the tag "v0.2.0" and all the micro release in that minor
> release (like `v0.2.1` `v0.2.2` and so on).
> Since every minorrelease branch contains all the tags in the
> minorrelease, you can push hotfixes to multiple minorreleases easily.
> Everything that is not minorrelease-specific happens in the `develop`
> branch. If it's a hotfix, it's cherry-picked inside that branches.
> 
> Sorry for having doubled the confusion.
> What do you think of my proposal anyway?

I like your proposal but I would suggest to simplify the actual
implementation for this project.
The case of supporting more than 1 stable version for libreant project
is fairly remote.
We use the master-develop branching model in avarage case and in special
case we'll decide to support multiple stable version we'll create the
release-* branches as you proposed.

Is it fine for you?

-- 
tommy.ael
gpg key: 0xEBD8B3682C4C4645

**Comment by boyska** [comment]
On Mon, Oct 26, 2015 at 04:51:28AM -0700, ael wrote:
>On 10/26/2015 12:16 PM, BoySka wrote:
>The hotfix could possibly be merged with many major version in order to
>produce multiple minor version (1.0 -> 1.1, 2.1 -> 2.1.1, 3.0 -> 3.1)

uh? 1.0 plus a hotfix makes 1.0.1, not 1.1 (see [semantic
versioning](http://semver.org/) summary).

>Hence it should be named with a general hotfix name not linked to any
>particular minor version.

ok, so it's actually just like a feature-branch, not a permanent thing
that "follows" a release. Ok.

>The actual name of the hotfix-elasticsearch-vrs should be fine.

yes

>> So maybe I was getting it wrong. I propose that instead every minor
>> release get its own branch. I'd call it "release-0.2" rather than
>> "hotfix-0.2", but it's just naming.
>> [...]
>> What do you think of my proposal anyway?
>
>I like your proposal but I would suggest to simplify the actual
>implementation for this project.
>The case of supporting more than 1 stable version for libreant project
>is fairly remote.
>We use the master-develop branching model in avarage case and in special
>case we'll decide to support multiple stable version we'll create the
>release-* branches as you proposed.

Yes, this sounds reasonable. So we'll go this:
* master is now something like "latest version" ever, just as in the
  master/develop model
* If we want to backport a fix for an older release we create a
  release-branch starting from the release-tag, cherry-pick the fix
  right there, bump the microversion, and make a tag right there.

I think that this kind of things will happen after we'll release 1.0.0

And now, a quote from semver.org:

>>How do I know when to release 1.0.0?
>If your software is being used in production, it should probably already
>be 1.0.0. If you have a stable API on which users have come to depend,
>you should be 1.0.0. If you're worrying a lot about backwards
>compatibility, you should probably already be 1.0.0.

**Comment by boyska** [comment]
libreant.rtfd.org should be updated to reflect those changes. At now we have `latest` and `stable`, plus every possible tag. stable is mostly the same as `master`, while `latest` should point to `dev`.

**Comment by ael-code** [comment]
> libreant.rtfd.org should be updated to reflect those changes. At now we have latest and stable, plus every possible tag. stable is mostly the same as master, while latest should point to dev.

Now latest point to `dev` branch. Check if it's all as expected and give some feedback pls.

**Comment by boyska** [comment]
ael wrote:
>Now latest point to `dev` branch. Check if it's all as expected and give some feedback pls.

I don't think there is much difference I can compare. When someone
merges #210 it will be clearer ;)

**Comment by boyska** [comment]
Ok, now that #210 has been merged I can confirm the new setup of http://libreant.rtfd.org/
