### ISSUE TITLE
Duplicate membership to a group

### ISSUE THREAD

**Issue by boyska** [insomnia-lab/libreant#205]
It is currently possible to add a user two times to the same group. This will not only not result in an exception (which can be ok) but will actually duplicate lines on db.

Lucky thing is that if you add a user three times to a group, it can anyway be removed with only one `remove_user_from_group`, so behvaiorally everything is nice.

Still I see it as a source of future bugs.

**Comment by ael-code** [comment]
> It is currently possible to add a user two times to the same group. This will not only not result in an exception (which can be ok) but will actually duplicate lines on db.
Ohoho. No good.

I created a branch with additional tests for this issue:
https://github.com/ael-code/libreant/commits/205-duplicate-membership

It happen also for `CapabilityToGroup` relation.

**Comment by ael-code** [comment]
fixed by #208
