### ISSUE TITLE
What's the point of forbidding two capability with same domain?

### ISSUE THREAD

**Issue by boyska** [insomnia-lab/libreant#206]
Here
https://github.com/insomnia-lab/libreant/commit/07c7baab77eff5c19fc23efeda2001736c16846d#diff-6cbd4ce852aa92344f2c6eb0e3785748R110

we see that it is forbidden to create two capabilities with the same domain+action in the DB.

This means that if for example I have a capability on `attachments` with action `CR` and I want two groups to have it, then I MUST create it just once, and add it to multiple groups.
But then what does it mean to _update_ a capability? It will change it for multiple groups at once, so in practice I'd need to create a new one, and attach to a single group.

I am 90% convinced that it must be solved at the Model layer. Otherwise, the API layer can handle it. Keeping it like it is make the API about capabilities very hard to use for practical purposes.

Maybe related to #205

**Comment by ael-code** [comment]
On 10/30/2015 09:27 AM, BoySka wrote:
> Here
> 07c7baa#diff-6cbd4ce852aa92344f2c6eb0e3785748R110
> <https://github.com/insomnia-lab/libreant/commit/07c7baab77eff5c19fc23efeda2001736c16846d#diff-6cbd4ce852aa92344f2c6eb0e3785748R110>
> 
> we see that it is forbidden to create two capabilities with the same
> domain+action in the DB.
> 
> This means that if for example I have a capability on |attachments| with
> action |CR| and I want two groups to have it, then I MUST create it just
> once, and add it to multiple groups.
> But then what does it mean to /update/ a capability? It will change it
> for multiple groups at once, so in practice I'd need to create a new
> one, and attach to a single group.
> 
> I am 90% convinced that it must be solved at the Model layer. Otherwise,
> the API layer can handle it. Keeping it like it is make the API about
> capabilities very hard to use for practical purposes.

So are we going to remove the unique constraint from the Capability model?
We will have multiple capability with the same couple domain/action in
the db, but the management will be easier.

**Comment by boyska** [comment]
ael wrote:
>BoySka wrote:
>> we see that it is forbidden to create two capabilities with the same
>> domain+action in the DB.
>
>So are we going to remove the unique constraint from the Capability model?
>We will have multiple capability with the same couple domain/action in
>the db, but the management will be easier.

yep! (the only other solution would be the removal of
users.api.update_capability)
