### ISSUE TITLE
DB structure documentation code

### ISSUE THREAD

**Issue by ael-code** [insomnia-lab/libreant#21]
missing wiki page with database object structure description.

**Comment by boyska** [comment]
I think that this is better documented in the code.

I will keep the wiki just for instructions on how to get used to hacking the code, how to use github properly, and this kind of _meta_ things.

**Comment by ael-code** [comment]
those info will be useful also for the end user/admin
Do you really want to put them in the code? 
Where would you like to insert this stuff? In which file?

**Comment by boyska** [comment]
Does the end user needs the object structure of the database? I mean, he _could_ be interested, but is that a user-faced docuemntation? I don't believe so, but duplicating may be ok.

I'd put these things for sure under `libreantdb/`; probably under `api.py` or `__init__.py`

**Comment by ael-code** [comment]
oke... after that #22 will be merged, I'll put pep 257 doc in ```api.py```

**Comment by boyska** [comment]
we now have a proper documentation system, so writing this should immediately produce an html documentation. Yay! Putting this in 0.2 milestone, too.

**Comment by boyska** [comment]
Yesterday we proposed that you could be the one documenting this: you have a clear understanding of the DB, about elasticsearch API, and all this stuff. You are free to refuse, and we will blame you forever :P
