### ISSUE TITLE
Documentation and Continous Integration

### ISSUE THREAD

**Issue by boyska** [insomnia-lab/libreant#212]
At the moment we have readthedocs continually integrated with our main branches, so we have always up-to-date documentation.
We also have Travis CI automatically testing our pull requests, which is a nice way to get early feedback.

Could we have documentation for pull requests automatically built? this way it would be much easier to check if (let's say) a docsting markup is messed up.

**Comment by ael-code** [comment]
On 11/02/2015 03:23 PM, BoySka wrote:
> At the moment we have readthedocs continually integrated with our main
> branches, so we have always up-to-date documentation.
> We also have Travis CI automatically testing our pull requests, which is
> a nice way to get early feedback.
> 
> Could we have documentation for pull requests automatically built? this
> way it would be much easier to check if (let's say) a docsting markup is
> messed up.

I think it's not possible to automatically trigger rtfd on PR.

You can always set rtfd to automatically build  branch of your repo.

One other nice thing to do could be to make Travis check if the
`build_doc` command raise any error.

**Comment by boyska** [comment]
>  One other nice thing to do could be to make Travis check if the `build_doc` command raise any error.

This is not really related, since it will not give us the output of `build_sphinx` (I guess you meant `build_sphinx`, not `build_doc`), but only check if the documentation builds correctly.

Would be useful anyway.

**Comment by boyska** [comment]
I implemented it in #215

**Comment by boyska** [comment]
I believe there is not much we can do, so even if this is desirable, I'll close this.

**Comment by boyska** [comment]
Ok, I discovered how to do this. We just need to setup some command that does the upload (like scp) to some server we own, in the `after_success` section. Here is [an example](https://github.com/Uko/Rubidium-WHOIS/blob/master/.travis.yml) and [some doc](https://docs.travis-ci.com/user/deployment/custom/)
