### ISSUE TITLE
Create a debian package

### ISSUE THREAD

**Issue by boyska** [insomnia-lab/libreant#229]
This should actually *not* be part of this repository, but seems natural to file it here.

A debian package is not only a convenient way to install libreant, but also ensures us the possibility of doing distribution-specific hacks (like we had for gevent) without "dirtying" our upstream source code.

Related to #227

**Comment by boyska** [comment]
The following packages are missing in debian:
* python-peewee
* python-flask-bootstrap
* python-flask-authbone
* python-opensearch
* python-fsdb

I started working on some of them, hope nothing really difficult come out!

**Comment by ael-code** [comment]
On Dec 8, 2015 11:05, "BoySka" <notifications@github.com> wrote:
>
> This should actually not be part of this repository, but seems natural to
file it here.
>

So where are we gonna put the distro specific stuff?

**Comment by boyska** [comment]
On Sun, Dec 13, 2015 at 02:08:25AM -0800, ael wrote:
>On Dec 8, 2015 11:05, "BoySka" <notifications@github.com> wrote:
>>
>> This should actually not be part of this repository, but seems natural to
>file it here.
>>
>
>So where are we gonna put the distro specific stuff?

In another repository.
Debian suggests _not_ to put the debian/ directory in the upstream
source, even if debian package maintainer and software developer is the
same person.
This makes sense and is more coherent with how I am doing lot of other
debian packages on which libreant depends.

-- 
boyska

**Comment by boyska** [comment]
btw, I managed to create all the needed packages, and libreant appears to work on a clean test system, just running `apt-get install python-libreant`. yay!

**Comment by boyska** [comment]
@ael-code for this to go further I'd really need a recent version to be released, even if just as alpha version. Can we call the current origin/dev 0.3alpha1 ? Or, can we set exact goals about when to release 0.3?

**Comment by boyska** [comment]
check this out! http://git.lattuga.net/boyska/deb-libreant

It has lot of other dependencies, and  all of them are (should?) be in my account http://git.lattuga.net/boyska
YES, it is not github. I'm hosting those there because:
* while in libreant we were seeking maximum collaboration from 3rd parties, and thus github was a proper choice, the same motivation does not apply to debian packages
* of a sentiment we expressed in the last few meetings
* we can switch at any time. If you prefer everything to stay on github, or if we have any motivation not to stay on git.lattuga.net, I can be ok with it.
* ![Fuck yeah](https://gogs.io/img/favicon.ico)

When I can, I'll create a debian repsitory for it. Please note that I created everything for debian testing (stretch), not for debian stable (jessie). I think it should be easy to do all the same for debian stable, but I started with testing because some dependencies were already present. Could be backported, though.

**Comment by boyska** [comment]
I think that we can consider this closed by  http://git.lattuga.net/boyska/deb-libreant
