### ISSUE TITLE
agherant doc

### ISSUE THREAD

**Issue by ael-code** [insomnia-lab/libreant#23]
We should write a wiki page dedicated to agherant.
How it works and how to configure it

**Comment by boyska** [comment]
See also #21 
I believe that we should have a decision about what should be documented how/where.

IMHO, we should create a `doc/` directory using sphinx to document code, APIs, installation, user configurations, etc. I am also willing to create the skeleton and start some scratch of documentation.
I believe that we should leave the wiki for random notes making the development/contribution easier.

Specifically to this issue, I believe this should be in the user documentation (ie: in `doc/` and not in the wiki)

**Comment by ael-code** [comment]
I agree

**Comment by boyska** [comment]
#64 introduced the `doc/` directory, so we're now ready to write documentation. I think that we'd better discuss documentation organization live and alltogether, though.

**Comment by boyska** [comment]
Unfortunately github does not allow two assignees, but this is really also assigned to @mgdl
