### ISSUE TITLE
version in code is behind PyPI

### ISSUE THREAD

**Issue by boyska** [insomnia-lab/libreant#233]
On PyPI, latest version is 0.2.2, released on october.
But in the code I see that the version is 0.2.1. I guess that the version bump has never been commited. What shall we do?

**Comment by ael-code** [comment]
the version on master is coherent [df246a0662d25a2bc933bcb3ba2ce632f9d8be9a] but on the dev branch isn't. This is due to how I applied the branching model. Should we change something in the branching flow?

**Comment by boyska** [comment]
Oh! I think that in the `dev` branch versions are not so important, so it could be ok even this way. I find it a bit confusing, but ok.
