### ISSUE TITLE
Adjust code for parsing json on Flask 1.0

### ISSUE THREAD

**Issue by ael-code** [insomnia-lab/libreant#247]
On Flask `0.10`, the exposed facilities for parsing json encoded request's body are buggish. For example you can look at https://github.com/mitsuhiko/flask/blob/0.10-maintenance/flask/wrappers.py#L127.

In Flask `1.0` this code has been improved, thus when we'll switch to the new version we could make our code  much way better.

**Comment by boyska** [comment]
Probably you are aware of it, but keep in mind that debian still has version `0.10` in all its releases (yes, even on experimental), so unless there are really strong reasons for it, I'd keep everything compatible with `0.10`. Maybe it's time for us to

1. write unit tests for the webui, at least for the seemingly more fragile parts
2. get unit tests performed on both `0.10` and `1.0`

?

**Comment by boyska** [comment]
is this bug still valid? I see it has been referenced on #250 (which has been merged), but I have not really checked the code

**Comment by ael-code** [comment]
Has been fixed by #248
