### ISSUE TITLE
dependencies: gevent 1.1.0 has been released

### ISSUE THREAD

**Issue by ael-code** [insomnia-lab/libreant#259]
https://github.com/gevent/gevent/releases/tag/v1.1.0

**Comment by boyska** [comment]
No breaking change, right?

**Comment by ael-code** [comment]
> No breaking change, right?

After some tests seems fine

**Comment by boyska** [comment]
so can we close this? I don't think we need to *act* on this.

**Comment by ael-code** [comment]
On 03/06/2016 10:10 PM, BoySka wrote:
> so can we close this? I don't think we need to /act/ on this.
> 

We need to update setup.py and travis conf.
We could do these stuff after #231 will be merged.
