### ISSUE TITLE
test multiple elasticsearch versions

### ISSUE THREAD

**Issue by boyska** [insomnia-lab/libreant#262]
We should automatically test that `libreantdb` works fine with different elasticsearch versions. Indeed, we are _expecting_ that this is the case, but we're only doing travis-ci testing against elasticsearch `1.4`. I'd like to test against multiple `1.x` version as well as against some `2.x` version. This case also requires changing the python library version.

**Comment by boyska** [comment]
See
https://github.com/travis-ci/apt-source-whitelist/blob/189b706dc54ccbdd99fae5489fcbc71ee1a918c5/ubuntu.json#L83
and the apt addon:
https://docs.travis-ci.com/user/installing-dependencies/#Adding-APT-Sources

**Comment by ael-code** [comment]
since 720522cad2de225423ed9f88508b38e5959fb7f6 we start testing the latest version of both `1.x` and `2.x`. Do we need something more?

**Comment by boyska** [comment]
oh, you're right. that's fine enough. I just wasn't realizing because the code is not that clear

**Comment by boyska** [comment]
In travis conf, we don't use travis builtin support for apt repositories because of
https://github.com/travis-ci/apt-source-whitelist/issues/190#issuecomment-240523194
this has now been solved
https://github.com/travis-ci/apt-source-whitelist/commit/a272145410446f5a8c98afb125be9f4d4de8afc6

So we could now improve the `travis/install_dependencies.sh` uglyness (not that I care so much about).
