### ISSUE TITLE
Securing REST api

### ISSUE THREAD

**Issue by ael-code** [insomnia-lab/libreant#287]
We can start discussing here on how to secure the REST api.

If you want to read something:
https://www.owasp.org/index.php/REST_Security_Cheat_Sheet#Authentication_and_session_management
http://stackoverflow.com/questions/319530/restful-authentication

**Comment by boyska** [comment]
First of all, what's the current status? I guess that as of now the only way the rest api is authenticated is logging in, getting a cookie and then using it for every rest api. Which is not very REST, but works.

I guess that this is slightly unpractical for machine-to-machine, so we might consider something like basic auth for that case. But the first question is what do we expect to do with those REST APIs.

**Comment by ael-code** [comment]
On 04/25/2016 04:21 PM, BoySka wrote:
> First of all, what's the current status? I guess that as of now the only
> way the rest api is authenticated is logging in, getting a cookie and
> then using it for every rest api. Which is not very REST, but works.
> 
At the moment the authentication/authorization layer is not used at all
for the rest API.

> I guess that this is slightly unpractical for machine-to-machine, so we
> might consider something like basic auth for that case. But the first
> question is what do we expect to do with those REST APIs.

The REST api are used by us in some parts of the web UI, but they can
also be used by third party applications, custom script, etc..

**Comment by boyska** [comment]
ael:
>On 04/25/2016 04:21 PM, BoySka wrote:
>> First of all, what's the current status? I guess that as of now the only
>> way the rest api is authenticated is logging in, getting a cookie and
>> then using it for every rest api. Which is not very REST, but works.
>>
>At the moment the authentication/authorization layer is not used at all
>for the rest API.

wait... what? I can do everything with the rest api without logging in?
seriously? that should be labeled as a huge security issue!

>> I guess that this is slightly unpractical for machine-to-machine, so we
>> might consider something like basic auth for that case. But the first
>> question is what do we expect to do with those REST APIs.
>
>The REST api are used by us in some parts of the web UI, but they can
>also be used by third party applications, custom script, etc..

Yes, I know the theory :) The point is, what do we want to make the API
good for.
If our priority is for the WebUI or applications that are much
integrated with libreant, then the cookie-based authentication is
enough.

If we want to also be nice to "simpler" kinds of integration, in which
an application wants to perform some operation on libreant but in the
quickest way possible because it's not its main focus, then we can
consider adding basic auth or other kinds of authentication.
An example of this could be some quick script on a librarian computer to
create users or books based on `curl+zenity`.

-- 
boyska

**Comment by ael-code** [comment]
On 04/26/2016 05:00 PM, BoySka wrote:
> ael:
>>On 04/25/2016 04:21 PM, BoySka wrote:
>>> First of all, what's the current status? I guess that as of now the only
>>> way the rest api is authenticated is logging in, getting a cookie and
>>> then using it for every rest api. Which is not very REST, but works.
>>>
>>At the moment the authentication/authorization layer is not used at all
>>for the rest API.
> 
> wait... what? I can do everything with the rest api without logging in?
> seriously? that should be labeled as a huge security issue!
> 

Yes. I'm serious the security layer has not been integrated with the
REST api.

I'll work on it in the next days.

>>> I guess that this is slightly unpractical for machine-to-machine, so we
>>> might consider something like basic auth for that case. But the first
>>> question is what do we expect to do with those REST APIs.
>>
>>The REST api are used by us in some parts of the web UI, but they can
>>also be used by third party applications, custom script, etc..
> 
> Yes, I know the theory :) The point is, what do we want to make the API
> good for.
> If our priority is for the WebUI or applications that are much
> integrated with libreant, then the cookie-based authentication is
> enough.
> 
> If we want to also be nice to "simpler" kinds of integration, in which
> an application wants to perform some operation on libreant but in the
> quickest way possible because it's not its main focus, then we can
> consider adding basic auth or other kinds of authentication.
> An example of this could be some quick script on a librarian computer to
> create users or books based on `curl+zenity`.

I'll start with the cookie based then we can add another authentication
method.

**Comment by boyska** [comment]
For the main developer **hip hip hooray!**
