### ISSUE TITLE
make elasticsearch 2.x the default choice

### ISSUE THREAD

**Issue by ael-code** [insomnia-lab/libreant#301]
Just to recap, here you have an overview of Elasticsearch version on various Linux distros:
- Arch: `2.3.3`
- Debian Jessie (stable): `1.0.3` but we usually use official Elasticsearch repo
- Debian Stretch (testing): `1.7.5`
- Ubuntu: `1.7.5`

We recently added support to Elasticsearch 2.x. But we still use the old version as default choice.
At some point we should update the python-elasticsearch dependency requirement and the Libreant installation docs in order to point to the new Elasticsearch 2.x version.

I've opened this PR in order to understand which are the reasons that prevent us from moving completely to the new Elasticsearch version.

**Comment by boyska** [comment]
ael:
> - Debian Jessie (stable): `1.0.3` but we usually use official Elasticsearch repo

Debian Jessie-backports: 1.6.2

>I've opened this PR in order to understand which are the reasons that prevent us from moving completely to the new Elasticsearch version.

I guess that a good move could be to first release the current code,
which supports both elasticsearch 1.x and elasticsearch 2.x, postponing
the hard requirement on 2.x till we really feel there is much benefit
from it. I'm all for making the transition as easy as possible for
sysadmins.

**Comment by boyska** [comment]
I think that this issue doesn't apply anymore: with the soon-arriving 0.5, new users will only use ES2-ready code, while old users will have an easy upgrade path to be able to use it, without needing to install anything different. I'm for closing this issue.

**Comment by ael-code** [comment]
In 75bdadaa6caf0e51c05edd240e3e37f9a29cd661 we've updated the documentation to point to elasticsearch `2.x` repository.
And also in the more recent a68479a07db60ae391b061c56c693fa890985fc2, we changed the default installed `pylasticsearch` version to `2.x`.

Thus I think that we can consider this issue solved.
