### ISSUE TITLE
restyle /search page

### ISSUE THREAD

**Issue by ael-code** [insomnia-lab/libreant#34]
enhancement:
 - leave search bar on top prefilled with last research query ( like big search engines do )
![search_bar_duck](https://cloud.githubusercontent.com/assets/4229536/5792361/a15dd676-9f15-11e4-9e9a-37a1a5c58c8b.png)

**Comment by frenko** [comment]
this issue is solved by #41 ?

**Comment by boyska** [comment]
I believed so. But @ael-code was not that sure. @ael-code can you clarify how is the situation in your opinion?

**Comment by ael-code** [comment]
updated ot

**Comment by boyska** [comment]
is this any different?

![libreant search](https://i.imgur.com/yI6SsmN.png)

sorry but I am failing in understanding the difference

**Comment by ael-code** [comment]
It's very simple.
According to me search bar is one of the most important thing inside this page. I would like to move the search bar from the navbar to the start of the page content.
On mobile device the navbar is collapsed and you have to open it every time you want to modify your query.

**Comment by boyska** [comment]
NOW I understand. ok that seems correct.

**Comment by frenko** [comment]
>NOW I understand. ok that seems correct.
quote!!
We can create a macro with searchbar like navbar?
