### ISSUE TITLE
load config from file

### ISSUE THREAD

**Issue by ael-code** [insomnia-lab/libreant#37]
Now configurations are loaded from environment variables.

What do you think about allowing admins to load webant configurations also from file.

**Comment by boyska** [comment]
It's already there. See AppConfig documentation ( https://pypi.python.org/pypi/flask-appconfig ):

>The application returned by create_app will, in order:
>
 >   Load default settings from a module called myapp.default_config, if it exists. (method described in http://flask.pocoo.org/docs/config/#configuring-from-files )
    Load settings from a configuration file whose name is given in the environment variable MYAPP_CONFIG (see link from 1.).
    Load json or string values directly from environment variables that start with a prefix of MYAPP_, i.e. setting MYAPP_SQLALCHEMY_ECHO=true will cause the setting of SQLALCHEMY_ECHO to be True.

I believe that this can be closed
