### ISSUE TITLE
fsdb path

### ISSUE THREAD

**Issue by ael-code** [insomnia-lab/libreant#38]
Now fsdb path is hardcoded as ```/tmp/fsdbRoot```. This sucks.

Following other settings style we will allow to pass this specific config through variable ```WEBANT_FSDB_PATH```, but some questions need answers:
What should append if user do not pass fsdb path?
Which path should we use as the default one?

**Comment by boyska** [comment]
I'll do like this: if `DEBUG` is `True`, then default is `/tmp/fsdbRoot`. Otherwise, raise an Exception about missing config!
