### ISSUE TITLE
search page, wrong fields assumptions

### ISSUE THREAD

**Issue by frenko** [insomnia-lab/libreant#50]
In search page, if I use "generic preset" to add an item, don't show anything except a language field
![screenshot from 2015-01-16 17 17 40](https://cloud.githubusercontent.com/assets/6986802/5790738/1d63f616-9ea7-11e4-9d78-aecb128f2c40.png)
This happens because we assume that the fields used to be "actors" or "title" ([title](https://github.com/insomnia-lab/libreant/blob/master/webant/templates/search.html#L44) or [actors](https://github.com/insomnia-lab/libreant/blob/master/webant/templates/search.html#L52)) and in the "generic preset" these fields are not present by default. How can we solve this problem?

**Comment by boyska** [comment]
I don't think that this is wrong and solvable. If you have no metadata, how can we show something?
Probably the most correct way would be just to clearly state that "title" and "actors" are somewhat specials field, and include them in the basic preset.

I think that this should be a WONTFIX for now. Of course we can think of better ways to handle this issue (for example: if no `title` is found, then fallback to the concatenation of every other field, or any other craziness). But I wouldn't block the 0.1 release just for this.

**Comment by frenko** [comment]
>I think that this should be a WONTFIX for now. Of course we can think of better ways to handle this >issue (for example: if no title is found, then fallback to the concatenation of every other field, or any >other craziness). But I wouldn't block the 0.1 release just for this.

Ok, for now this is a WONTFIX. I remove this issue from Milestone 0.1.
Removing this issue the milestone is ready or not?

**Comment by boyska** [comment]
Yes, it is ready. Who wants to do the upload? :)

**Comment by ael-code** [comment]
> Removing this issue the milestone is ready or not?
yes:
https://github.com/insomnia-lab/libreant/milestones

> Yes, it is ready. Who wants to do the upload? :)
facci pure.

**Comment by frenko** [comment]
>facci pure.
yeah!

**Comment by boyska** [comment]
I'm going
