### ISSUE TITLE
Rest Api

### ISSUE THREAD

**Issue by ael-code** [insomnia-lab/libreant#52]
In order to make a good admin interface, we could use ajax calls and a rest interface.
We are using JSON everywhere, so I was thinking to use it also for the rest apis.

### Items interaction:
 
 - GET ```/v1/items/<item_id>```  
retrieve item
 - POST ```/v1/items/<item_id>```  
insert new item
 - PUT ```/v1/items/<item_id>```  
update an existing item
 - DELETE ```/v1/items/<item_id>```  
delete an existing item

### Items files interaction:
 - GET ```/v1/items/<item_id>/files ```  
retrieve files infos
 - GET ```/v1/items/<item_id>/files/<file_id>```  
retrieve a specific file
 
### Search items:
 - GET ```/v1/items?q=<query_string>&sort=< >&order=< >```  
search items (optionally ordered by ... )

### Users interaction:
 ?

**Comment by ael-code** [comment]
can we use [Blueprint](http://flask.pocoo.org/docs/0.10/blueprints/#blueprints) to implement api views.

**Comment by boyska** [comment]
Mh, but if we're putting the logic inside the app, then the Blueprint will have to access methods of `current_app`. But what's the point of a Blueprint that is not detachable from the application?

**Comment by ael-code** [comment]
Problem: posting metadata and file in a single HTTP POST request.

I'm implementing POST code for rest api. I think that the method we use in `POST /upload` is too complicated. I want to make a simpler and unified api interface.

I've made some research and I found out that there are a lot of complicated, ugly and not-well-supported solution.
One solution I really like is the one [adopted in Google drive API](https://developers.google.com/drive/web/manage-uploads#multipart), but it use `multipart/related` content-type that it's not supported by curl, flusk, postman and many other.
I'm thinking to use [this solution](http://stackoverflow.com/a/13076550) in which using `multipart/form-data` you will send metadata as json-formatted-string and binary data in the same reuqest. This type of content-type is well supported.

What do you think about last solution?
@boyska AFK you told me that you don't like this solution, isn't it?

**Comment by hellais** [comment]
I am going to leave this here: http://swagger.io/

**Comment by ael-code** [comment]
> I am going to leave this here: http://swagger.io/

I did not understood, your swagger hint is about 
`Problem: posting metadata and file in a single HTTP POST request.` or only a suggestion for documenting API?

Anyway I've used swagger 1.X in a previous project and I like it.

**Comment by ael-code** [comment]
> I'm thinking to use this solution in which using multipart/form-data you will send metadata as json-formatted-string and binary data in the same reuqest. This type of content-type is well supported.

I'm going to use this solution. If someone has some doubt, talk now!

**Comment by hellais** [comment]
@ael-code since you were discussion about designing a RESTful API, swagger is a good solution for said purpose. Moreover there are also code generators for a variety of different languages and frameworks (there are various swagger backed codegens for flask too).

I can't recommend a specific codegen for flask as I have not used those, but even if you don't  end up using the codegen aspect of it, it's still an excellent solution for having a well specified API and exposing documentation of it.
I can recommend the strongloop codegenerators for swagger that will make node.js serverside code and angular.js client side code.
