### ISSUE TITLE
include .mo (translations) in binary package

### ISSUE THREAD

**Issue by ael-code** [insomnia-lab/libreant#57]

**Comment by boyska** [comment]
look https://docs.python.org/2/library/gettext.html#id9 !
seems like the solutions we found deluge was using (including [msgfmt.py](https://github.com/zeroware/deluge/blob/d3f47097c1e74d5a6a69b808fcd695994a79ce44/msgfmt.py) in the code, so to avoid depending an external tools) is not a so-crazy one, but an almost-standard one.

**Comment by ael-code** [comment]
let's do it

**Comment by boyska** [comment]
can you do it? :D

**Comment by ael-code** [comment]
I'll try
