### ISSUE TITLE
Skeleton field and filter

### ISSUE THREAD

**Issue by g3-3k** [insomnia-lab/libreant#58]
For a simple insertion and search in a library with many kinds of book the skeleton is a powerfull tool
We could create a field for the skeleton choosed for the book. this will be usefull in case of totally different kind of books (comics, book, opuscoli, etc... ) and leave as "unknown" in case of emptyness, then live the "editor" the responsability of checking and improve. the user will be helped in searching through a color legend for each skeleton
I m not totally sure this is a good idea.

**Comment by boyska** [comment]
This is not a single thing.
I can surely decompose it in:
* apply different visualization based on some fields
* skeleton support for prefilled fields

I don't understand what you mean with "then live the "editor" the responsability of checking and improve"

**Comment by g3-3k** [comment]
we need to debate about
