### ISSUE TITLE
type field

### ISSUE THREAD

**Issue by g3-3k** [insomnia-lab/libreant#59]
From the previous issue I got this idea that is much better :)
We could create the field "avaibility" or "type" in which distinguish from 3 macro format, paper for sell, paper for customer and digital:; and make this field compulsory.
3 basic points:
-user can chose which type he wants to look for
-agherant can "export" from different nodes only digital item
-user can add only digital item (since only the library admin can add the other types)

**Comment by boyska** [comment]
On Mon, Jan 19, 2015 at 04:12:02AM -0800, g3-3k wrote:
>We could create the field "avaibility" or "type" in which distinguish
>from 3 macro format, paper for sell, paper for customer and digital:;
>and make this field compulsory.

what do you mean? A field is created by those that are running the
nodes. This issue tracker is for developing libreant.

>-user can chose which type he wants to look for

this can already be done

>-agherant can "export" from different nodes only digital item

agherant never exports anything. Actually it doesn't import, either.

>-user can add only digital item (since only the library admin can add the other types)

by now, we have NO way to handle users and permissions.
When we'll have, site managers can decide what is allowed and what is not.

-- 
boyska

**Comment by g3-3k** [comment]
>what do you mean? A field is created by those that are running the nodes. This issue tracker is for developing libreant.
yes, create a compulsory field as language is part of developing

>agherant never exports anything. Actually it doesn't import, either.
Hope in a short future it will "import" too, couse pretty useless to know wich digital books are 4 hours of train away.
>by now, we have NO way to handle users and permissions.
>When we'll have, site managers can decide what is allowed and what is not.
We ll have, and it s a different issue. It s to motivate this choiche I made this consideration.

**Comment by boyska** [comment]
On Mon, Jan 19, 2015 at 04:24:47AM -0800, g3-3k wrote:
>>what do you mean? A field is created by those that are running the nodes. This issue tracker is for developing libreant.
>yes, create a compulsory field as language is part of developing

no, it's not. It's part of "create your own skeleton, for your own
needs". We already have skeletons that support mandatory fields, so
what's the point?

Language is a different thing: without that information, the DB can't
work properly. That's the only reason why it is mandatory.

And by the way, I don't give a fuck about inserting support for selling
stuff.

>>agherant never exports anything. Actually it doesn't import, either.
>Hope in a short future it will "import" too, couse pretty useless to
>know wich digital books are 4 hours of train away.

Agherant is an openserach aggregator. It can't import anything. It's not
even bound to a libreant node.
Please, you should really understand what's the current architecture.
Let's document it together, and probably everything will be more clear!

The "import" thing is between libreant nodes, not between aggregators.

>>by now, we have NO way to handle users and permissions.
>>When we'll have, site managers can decide what is allowed and what is not.
>We ll have, and it s a different issue. It s to motivate this choiche I
>made this consideration.

ok but the user can choose the configuration by himself. It's not
something that we should develop.

But sure it is ok to have fine-grained permissions, so that the site
manager can be very selective about what any user can do.

-- 
boyska

**Comment by g3-3k** [comment]
> no, it's not. It's part of "create your own skeleton, for your own
> needs". We already have skeletons that support mandatory fields, so
> what's the point?
>
to create a field who is the same for all skeleton and the values are in
a list (digital, customer, selling, and few more)

> And by the way, I don't give a fuck about inserting support for selling
> stuff.
>
To divide between selling stuff and all the rest is the best way to make
the user, who will interface in a "info point"., a "sell-free" research.
moreover the crucial point it s about digital items.

> >>agherant never exports anything. Actually it doesn't import, either.
> >Hope in a short future it will "import" too, couse pretty useless to
> >know wich digital books are 4 hours of train away.
>
> Agherant is an openserach aggregator. It can't import anything. It's not
> even bound to a libreant node.
> Please, you should really understand what's the current architecture.
> Let's document it together, and probably everything will be more clear!
>
that's true

> ok but the user can choose the configuration by himself. It's not
> something that we should develop.
Fine, still it wasn't for user-managing develop.


-- 
Easy is the way for the Dark Side
mit dot eu
0xDF6EA30E

**Comment by boyska** [comment]
We debated about this issue. I think the conclusion was:
* #70 will solve this from the "insertion" point of view
* it is needed to also have a mechanism to configure how a node appears based on some metadata. For example, it should be possible to say "where distributionmethod=consultationroom -> add a nice icon"
