### ISSUE TITLE
Login, authentication, permissions

### ISSUE THREAD

**Issue by boyska** [insomnia-lab/libreant#6]
We need to have some basic support to recognize authorized users. Apart from the classical login/authentication/authorization, we could also want some other method to give authorization to users based on the IP they have, or similar properties.

This issue asks for a sql-backed authentication mechanism + authorization helpers.

Authentication through IP address is not part of this issue (but should be kept in mind) (see #76 for that)

An admin page for managing users and permissions is not part of this issue (see #77 and #78 )

**Comment by boyska** [comment]
Yesterday, discussing live, we agreed that the easist thing is to use a sqlite backend for authentication. Writing our own "models" based on elasticsearch seems just not worth the effort, while for sqlalchemy there are lot of things ready to use.

We should now decide on which extension to use to provide authentication, and how to have authorization.

**Comment by boyska** [comment]
@hellais was interested in this, IIRC

**Comment by hellais** [comment]
Yes I confirm my interest in working on this. Probably what is needed is integrating something like:

http://flask.pocoo.org/snippets/86/

or

https://flask-login.readthedocs.org/en/latest/

What is the point of view of adding third party dependencies vs re-implementing something ourselves?

**Comment by boyska** [comment]
Great @hellais !
We usually said that using third party dependency is ok to avoid reinventing the wheel, if they are well-maintained, pip-installable and quite "standard". So I think that flask-login is ok.

**Comment by ael-code** [comment]
The back-end for users management it almost complete:  #189 and #195 were already merged and #196 it on the way.

I'm working at views level right now (webant).

How do you think should be the user registration process?

**Comment by boyska** [comment]
On a meeting, we decided that user registration could be a future enchancement, but is not at all a priority right now: there is no foreseeable usecase about creating a user yourself.

Instead, we decided that:
* When no "user db" is provided, anyone will have admin capabilities automatically. This is for testing, or when you are only binding webant to localhost
* When you specify a "user db", two special users will be created: `anonymous` and `admin`. Those are regular users, the only special thing is that they are automatically created. So it's straightforward to run libreant, login with `admin/defaultPassword`, change the password, and your libreant node is ready!

**Comment by hellais** [comment]
Thanks for tagging me! Will check it out when I have some time to breath. :hear_no_evil: :heart:

**Comment by hellais** [comment]
Can you remind me the IRC Channel and network (I am hellais on oftc, freenode and autistici)

**Comment by ael-code** [comment]
@hellais you was tagged 9 months ago :)

We already merged #189, #203 is on the way and I've already implemented the integration with flask. Hence we've almost done with this part.

Anyway it will be nice to have your feedback on future pull requests.

**Comment by ael-code** [comment]
We have implemented last piece of users/auth in 22de90354a3a0346335afa824259d30992247282.
We still miiss:
 - Authentication through IP address is not part of this issue (but should be kept in mind) (see #76 for that)
 - An admin page for managing users and permissions is not part of this issue (see #77 and #78 )

But they have their own issue
