### ISSUE TITLE
handle elasticsearch connection error

### ISSUE THREAD

**Issue by ael-code** [insomnia-lab/libreant#62]
In debug mode the error is handled by the flask debugger.
In standard mode the error cause 500 standard error page of flask to be rendered. 

Maybe we could give a more detailed message. It's a very common case.

**Comment by boyska** [comment]
isn't this correct?
a db failure is a typical "internal server error"

-- 
boyska

**Comment by ael-code** [comment]
yes... but extra infos do not cost money to us and improve the lives of the sysadmin ;)

**Comment by boyska** [comment]
oh, yes. But I believe that those should be handled in logging, not presented to the user. Surely not in production.

**Comment by ael-code** [comment]
> oh, yes. But I believe that those should be handled in logging, not presented to the user. Surely not in production.

I agree

**Comment by ael-code** [comment]
These are the exceptions raised from elasticsearch class:
https://elasticsearch-py.readthedocs.org/en/master/exceptions.html

Which of them we want to catch and log?

We can [register an error handler](http://flask.pocoo.org/docs/0.10/patterns/apierrors/#registering-an-error-handler) for the [ElasticsearchException](https://elasticsearch-py.readthedocs.org/en/master/exceptions.html#elasticsearch.ElasticsearchException) base class and then use [isinstance](https://docs.python.org/2/library/functions.html#isinstance) to filter them.

Do you like it?

**Comment by boyska** [comment]
wow, errorhandler seems a cool thing. I won't go into much details about the precise exception: after all, we just need to _log_ them. So maybe for any elasticsearch exception we'll just log "DB error" plus some info and the exact details / traceback.

**Comment by ael-code** [comment]
e20ab58edb1a528e534ccc86d868c72aaef473e3 added handler only for ```ConnectionError```.
We should implement some more generic handler.

**Comment by boyska** [comment]
@ael-code you mean "more generic" but still db-related? or do you mean handling Exception? I'm in favor of the first, but not so much of the second: if you are completely generic about error, then "500 Internal server error" is a good message.

**Comment by boyska** [comment]
reading http://elasticsearch-py.readthedocs.org/en/master/exceptions.html it seems that there is one parent for "almost all" classes, that is `Elastic`earchException`. The only exception that is not a child of this, is `ImproperlyConfigured`.
I had a quick grep inside elasticsearch code, and found that it is raised when the library is used with wrong parameters. So when we find that exception, we are actually discovering bugs in our code.

Summary: I propose to handle every `ElasticsearchException` just like we do with `ConnectionError` right now. `ImproperlyConfigured` should not be handled, so that it will result in a generic Internal Server Error message.

**Comment by ael-code** [comment]
I have proposed the following solution some comments ago:

> We can register an error handler for the ElasticsearchException base class and then use isinstance to filter them.

**Comment by boyska** [comment]
I don't see the need for filtering them. From a visitor point of view, "DB error" is more than enough; actually, even "Internal server error" would be ok to them.

If you want to debug what's wrong, you just need to watch the logs, where you should find some informative message, and maybe a traceback.
So I think we just need to cover more db-related exceptions, and add more useful logging.

**Comment by ael-code** [comment]
fixed long time ago in #104 by e20ab58edb1a528e534ccc86d868c72aaef473e3
