### ISSUE TITLE
missing documentation ref in README

### ISSUE THREAD

**Issue by ael-code** [insomnia-lab/libreant#65]
we need a new section in the README that points to http://libreant.readthedocs.org

**Comment by boyska** [comment]
We need a **badge**!

**Comment by boyska** [comment]
And here it is:
![libreant documentation ](https://readthedocs.org/projects/libreant/badge/?version=latest)

**Comment by ael-code** [comment]
I think that using only a badge, it's not very clear. I prefer using both badge and README entry

**Comment by boyska** [comment]
ok! I believe that documentation link should be one of the first thing we say!
