### ISSUE TITLE
stored files after database insertion error

### ISSUE THREAD

**Issue by ael-code** [insomnia-lab/libreant#69]
when file is uploaded, we store it and only after that we insert metadata on db.
If insertion on database goes wrong (ex: elasticsearch not started), we keep file on disk (Fsdb) without a relative entry into the database.

We should remove file on disk if database interaction raise errors/exceptions.

**Comment by boyska** [comment]
In implementing this, we should really be careful about removing, because it might be the case that a file with the same sha1 was already present.
