### ISSUE TITLE
add skeleton enum field

### ISSUE THREAD

**Issue by ael-code** [insomnia-lab/libreant#70]
we miss option to insert a field with presetted values through skeleton.

Example:
Una biblioteca decide di dividere i suoi libri in tre categorie:
 - tecnici
 - per bambini
 - romanzi

**Comment by boyska** [comment]
This is related to #53

**Comment by frenko** [comment]
why this is related to #53?? I don't understand!

**Comment by boyska** [comment]
sorry, it was #59. Edited.
