### ISSUE TITLE
Reorganizing view

### ISSUE THREAD

**Issue by ael-code** [insomnia-lab/libreant#73]
To solve both #26 and prepare code to implement #52 I will suggest to follow this:
https://exploreflask.com/blueprints.html#refactoring-small-apps-to-use-blueprints

the [where-do-you-put-them](https://exploreflask.com/blueprints.html#where-do-you-put-them) chapter explains some ways to organizing views. I prefer the "Divisional" way that is one used in [refactoring-small-apps-to-use-blueprints](https://exploreflask.com/blueprints.html#refactoring-small-apps-to-use-blueprints)

**Comment by boyska** [comment]
Very nice! I like the divisional one, too. So, to be clearer, in what parts do we want to split webant in?
* "user" part: home, search, view_book
* agherant
* API v1
* admin (by now it just has add_book, but who knows)

**Comment by ael-code** [comment]
@hellais I found your comment:
> Why are the routes defined inside of a function?
> I would suggest refactoring this to be inside of a separate module
> called api or webapi.

Can you give some more details about your suggestion?

**Comment by boyska** [comment]
Where is this comment? Btw, putting routes inside of a function is the "factory" method, which is very common pattern for flask. The point is that you might want to "inject" something into the application context, without making it global.

If you put routes inside of a module, they are global. This means that, for example, you cannot instantiate two different apps (why you would need such a thing, I don't know!) or that any resource they use must be global.

**Comment by hellais** [comment]
@boyska @ael-code this is based on what the flask author suggests for implementing a large flask app: https://github.com/mitsuhiko/flask/wiki/Large-app-how-to#first-view.

In particular he suggests using the Blueprint module to define the routes and views and then calling `register_blueprint` set it on the app.
This would also allow you to, as you were suggesting, instantiate two different apps.

The reason why I don't think it's a good idea to do it like it was being done, is that it leads to too many layers of nesting and to the definition of functions inline that I find to not be a good practice.

**Comment by boyska** [comment]
On Wed, Feb 25, 2015 at 06:58:33AM -0800, Arturo Filastò wrote:
>In particular he suggests using the Blueprint module to define the
>routes and views and then calling `register_blueprint` set it on the
>app.

we use blueprint a bit... we should use them more!

>This would also allow you to, as you were suggesting, instantiate two different apps.

wait, I am missing this point. How would a blueprint change anything?

>The reason why I don't think it's a good idea to do it like it was being done, is that it leads to too many layers of nesting and to the definition of functions inline that I find to not be a good practice.

what do you mean by "functions inline"? Why don't you consider them good
practice?

**Comment by ael-code** [comment]
we have implemented #52 using blueprint and soon or later we will modularize also agherant.
I'm going to close this issue.
