### ISSUE TITLE
agherant do not support localhost nodes

### ISSUE THREAD

**Issue by ael-code** [insomnia-lab/libreant#89]
We introduced ```SELF``` keyword in ```agherant_descriptions``` config to manage localhost nodes but at the moment we only support aggregation with node running on the same process/port.
We do not support aggreagation of local node running on different port

### Steps to reproduce the bug:
You need to have default ```ES_INDEX``` populated, 
run ```agherant``` and ```libreant``` on machine ```A```
and make query from a different machine ```B``` (the two machine must have different ip )

##### On machine A :
 - Launch agherant standalone on port 5001
   ```bash
WEBANT_PORT=5001 WEBANT_AGHERANT_DESCRIPTIONS='["http://localhost:5000/description.xml"]' agherant
```

 - Launch libreant with default  es_index on port 5000
    ```bash
webant
```

##### On machine B:
 - visit ``` http://ip-of-A:5001/agherant/search?q=*:* ```
 - click on some results

You will be redirected to somthing like:
> http://localhost:5000/DjdA8DAkjlJKAS

But should be something like:
> http://ip-of-A:5000/DjdA8DAkjlJKAS

### Possible solution:
Instead of replacing ```SELF``` keyword replace all localhost/127.0.0.1 found in ```AGHERANT_DESCRIPTIONS```

**Comment by boyska** [comment]
There's no solution for plain wrong configuration :)
what if they, for example, specify their locale network address, like `http://192.168.1.10:5000/?` what if they use a name that is resolved only locally, like `mymachine.mydomain.mytld`?

I think it will be crazy to fix all these sysadmin errors (that's what they are!); providing correct documentation seems like a better solution to me. This refers to #66

**Comment by ael-code** [comment]
How should be the right configuration for the given scenario?

**Comment by boyska** [comment]
It should be `http://fullyqualified.domain.name:5000/description.xml` instead of `http://localhost:5000/description.xml`.
