### ISSUE TITLE
agherant stand-alone with SELF

### ISSUE THREAD

**Issue by ael-code** [insomnia-lab/libreant#93]
If you launch agherant standalone with ```AGHERANT_DESCRIPTIONS='["SELF"]'``` and you try to search something a ```BuildError: ('description', {}, None)``` raises.

the problem is that 
```return url_for('description', _external=True)```
does not find 'description' endpoint because webant isn't started

maybe we can just skip ```SELF``` in this situation and warn the admin

**Comment by boyska** [comment]
Ok, I'll fix it logging a message about it and just skipping it

**Comment by boyska** [comment]
ok, pull request #94 can fix this
