### ISSUE TITLE
Db api tests fail

### ISSUE THREAD

**Issue by ael-code** [insomnia-lab/libreant#98]
both tests in ```libreantdb/test/test_length.py``` fail

```
ERROR: libreantdb.test.test_length.test_no_elements
-----------------------------------------------------------
Traceback (most recent call last):
  File "/home/libreant/libreant/ve/local/lib/python2.7/site-packages/nose-1.3.4-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/libreant/libreant/libreantdb/test/test_length.py", line 14, in test_no_elements
    eq_(len(db), 0)
  File "/home/libreant/libreant/libreantdb/api.py", line 112, in __len__
    return stats['indices'][self.index_name]['total']['docs']['count']
KeyError: 'test-book'

ERROR: libreantdb.test.test_length.test_one_element
-----------------------------------------------------------
Traceback (most recent call last):
  File "/home/libreant/libreant/ve/local/lib/python2.7/site-packages/nose-1.3.4-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/libreant/libreant/libreantdb/test/test_length.py", line 19, in test_one_element
    eq_(len(db), 0)
  File "/home/libreant/libreant/libreantdb/api.py", line 112, in __len__
    return stats['indices'][self.index_name]['total']['docs']['count']
KeyError: 'test-book'

```

**Comment by boyska** [comment]
On Sat, Feb 21, 2015 at 02:05:49AM -0800, ael wrote:
>both test in ```libreantdb/test/test_length.py``` fail

can't reproduce here.

seems like with_setup went wrong. Can you test it more than once? or
give any hints useful to debug?

**Comment by ael-code** [comment]
> Can you test it more than once?
They fail systematically.
> Give any hints useful to debug?
I do not have hints now.

**Comment by boyska** [comment]
On Sat, Feb 21, 2015 at 02:18:16AM -0800, ael wrote:
>They fail systematically.

ugh. Are you testing with `python setup.py test`, right?

**Comment by ael-code** [comment]
> ugh. Are you testing with `python setup.py test`, right?

nope
```nosetest -c nose.cfg```

**Comment by boyska** [comment]
You should use `python setup.py test` instead. I am now noticing that this information is missing from the documentation: I'll clarify it.

**Comment by ael-code** [comment]
Are not the same call?

**Comment by ael-code** [comment]
btw same result on both calling method

**Comment by boyska** [comment]
I sometime managed to reproduce this, but in random situations. Whenever I tried to debug, it disappeared. Even leaving the code all aloneWe have an Heisenbug!

This kind of bugs is usually related to timings, so I wonder whether the `.refresh` method is really working even for index creation.

I had some success in adding the following line to the `cleanall` function:

```python
db.es.indices.flush(index=db.index_name)
```

but I am not sure that this is really solving the problem. @ael-code can you test it, please?

**Comment by boyska** [comment]
Properly opened a pull request: testing my solution should be simpler now

**Comment by ael-code** [comment]
nope. Error persist

**Comment by boyska** [comment]
...apart from the fact that it sucks, you mean :P
what about
```python
db.es.indices.flush(index='_all')
```
?

**Comment by ael-code** [comment]
I tried to run all the tests without deleting and creating the ```test-book``` index between every test and all tests passed, and finished very quickly.
Are you sure we need to create and delete the index on every ```cleanall()```

**Comment by boyska** [comment]
Mh, which line did you delete? the index deletion _could_ maybe be avoided, but I don't know if the `delete_by_query` is actually enough for tests to be correct.
The best thing would be to create a different index for each test, so that they could even run in parallel, and stuff like that. I'm now making some experiments about it.

**Comment by ael-code** [comment]
I deleted those two lines:
https://github.com/insomnia-lab/libreant/blob/master/libreantdb/test/__init__.py#L25-26

> but I don't know if the delete_by_query is actually enough for tests to be correct.

They passed all.
